Repository cyberofficial/Synthalingua, pull requests merged in 2023-08, with the labels that each got.

#42 Point GitHubRepo to right Repo
  transcribe_audio.py
Labels: minor issue

#47 Dev testing -> Master
  README.md
  modules/__pycache__/about.cpython-310.pyc
  modules/__pycache__/audio.cpython-310.pyc
  modules/__pycache__/console_settings.cpython-310.pyc
  modules/__pycache__/discord.cpython-310.pyc
  modules/__pycache__/languages.cpython-310.pyc
  modules/__pycache__/model_downloader.cpython-310.pyc
  modules/__pycache__/parser_args.cpython-310.pyc
  modules/__pycache__/version_checker.cpython-310.pyc
  modules/__pycache__/warnings.cpython-310.pyc
  modules/about.py
  modules/console_settings.py
  modules/discord.py
  modules/languages.py
  modules/model_downloader.py
  modules/parser_args.py
  modules/version_checker.py
  modules/warnings.py
  transcribe_audio.py
  transcribe_audio.spec
Labels: enhancement, enhancement implemented, bug fix

#52 Var:"reset_text" called before set
  modules/version_checker.py
  transcribe_audio.py
Labels: bug fix
