Repository cyberofficial/Synthalingua, pull requests merged in 2024-03, with the labels that each got.

#83 Update README.md - correct typo
  README.md
Labels: documentation, fixed in next update, PR Forward

#91 Dev testing -> Main | GUI Update
  Synthalingua_Wrapper/App.config
  Synthalingua_Wrapper/MainUI.Designer.vb
  Synthalingua_Wrapper/MainUI.vb
  Synthalingua_Wrapper/My Project/Settings.Designer.vb
  Synthalingua_Wrapper/My Project/Settings.settings
  Synthalingua_Wrapper/Synthalingua_Wrapper.vbproj
  modules/sub_gen.py
  requirements.txt
  requirements_dev.txt
Labels: enhancement

#94 GUI Update Fixes
  Synthalingua_Wrapper/MainUI.vb
  Synthalingua_Wrapper/My Project/PublishProfiles/FolderProfile1.pubxml.user
  Synthalingua_Wrapper/subtitlewindow.Designer.vb
  Synthalingua_Wrapper/subtitlewindow.vb
  modules/version_checker.py
Labels: enhancement, bug fix
